This is makeindex, version 2.15 [MiKTeX 21.8].
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (40 entries accepted, 0 rejected).
Sorting entries....done (240 comparisons).
Generating output file thesis.acr....done (31 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
