# This is a basic workflow to help you get started with Actions

name: Build Master Thesis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            chktex -q -eall -n 8 -n 22 -n 24 -n 30 -n 44 -n 46 thesis.tex

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latexmk -bibtex -pdf -pdflatex="pdflatex -interaction=nonstopmode" thesis.tex
